entityName: 'Categoria'
entity: 'Blog\BlogBundle\Entity\Categoria'
repository: 'BlogBundle:Categoria'
index: 'admin_categoria'
new: 'admin_categoria_new'
edit: 'admin_categoria_edit'
show: 'admin_categoria_show'
create: 'admin_categoria_create'
update: 'admin_categoria_update'
delete: 'admin_categoria_delete'
export: 'admin_categoria_export'
sessionFilter: 'CategoriaControllerFilter'
fieldsindex:    
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        export: true    
    a.categoria:
        label: 'Categoria'
        name: 'Categoria'
        type: 'string'
        export: true    
    a.descripcion:
        label: 'Descripcion'
        name: 'Descripcion'
        type: 'string'
        export: true
fieldsshow:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
    a.categoria:
        label: 'Categoria'
        name: 'Categoria'
        type: 'string'
    a.descripcion:
        label: 'Descripcion'
        name: 'Descripcion'
        type: 'string'
    a.posts:
        label: 'Posts'
        name: 'Posts'
        type: 'ONE_TO_MANY'