entityName: 'Tag'
entity: 'Blog\BlogBundle\Entity\Tag'
repository: 'BlogBundle:Tag'
index: 'admin_tag'
new: 'admin_tag_new'
edit: 'admin_tag_edit'
show: 'admin_tag_show'
create: 'admin_tag_create'
update: 'admin_tag_update'
delete: 'admin_tag_delete'
export: 'admin_tag_export'
sessionFilter: 'TagControllerFilter'
fieldsindex:    
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        export: true    
    a.tag:
        label: 'Tag'
        name: 'Tag'
        type: 'string'
        export: true
fieldsshow:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
    a.tag:
        label: 'Tag'
        name: 'Tag'
        type: 'string'
    a.posts:
        label: 'Posts'
        name: 'Posts'
        type: 'MANY_TO_MANY'