blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

mw_simple_admin_crud:
    resource: "@MWSimpleAdminCrudBundle/Controller/"
    type:     annotation
    prefix:   /admin

# DEBE IR AL FINAL
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: MWSimpleAdminCrudBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*\/$
        _method: GET